# Libreries

In [1]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout, Input, BatchNormalization, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers
import numpy as np
from itertools import product

In [2]:
from tensorflow.keras.applications import (
    VGG19,
    ResNet50,
    DenseNet121
)

from tensorflow.keras.applications import (
    vgg19,
    resnet50,
    densenet
)

In [3]:
import google.colab
google.colab.drive.mount('/content/drive')

Mounted at /content/drive

# Definitions

In [4]:
path = "/content/drive/My Drive/Investigacion/UTN/GIBIO/Datasets/Dataset_smpl" #directory of the data
save_path= "/content/drive/My Drive/Investigacion/UTN/GIBIO/Results"
batch_size=350
train_size=0.7
val_size=0.15

## Load dataset

In [5]:
column_names = [
    "chest_circ", "waist_circ", "pelvis_circ", "neck_circ", "bicep_circ", "thigh_circ",
    "knee_circ", "arm_length", "leg_length", "calf_length", "head_circ", "wrist_circ",
    "arm_span", "shoulders_width", "torso_length", "inner_leg"
]

male_data = pd.read_csv(path + "/Annotations/bodymeasurements_m.csv", names=column_names)
female_data = pd.read_csv(path + "/Annotations/bodymeasurements_f.csv", names=column_names)
male_data.insert(0, "ID", [f"men/{i:06d}.png" for i in range(len(male_data))])
female_data.insert(0, "ID", [f"women/{i:06d}.png" for i in range(len(female_data))])

In [6]:
male_data.head(5)

,ID,chest_circ,waist_circ,pelvis_circ,neck_circ,bicep_circ,thigh_circ,knee_circ,arm_length,leg_length,calf_length,head_circ,wrist_circ,arm_span,shoulders_width,torso_length,inner_leg
0,men/000000.png,83.576515,73.213088,92.503097,36.068310,22.853661,46.370356,35.224242,55.186850,84.096402,43.584922,53.987637,15.808483,182.0555,34.255001,49.249297,77.946905
1,men/000001.png,101.702204,88.686590,100.846918,38.591906,28.510385,53.521642,37.731078,49.606380,73.995692,38.563633,57.345473,15.794436,171.1829,36.272103,51.644093,67.475005
2,men/000002.png,104.289594,97.596672,100.898346,43.369495,28.740368,50.741101,37.595967,47.996426,71.371871,36.863151,60.638029,17.591052,170.2976,37.544197,50.525796,67.803296
3,men/000003.png,118.734385,117.314673,118.804251,47.740865,38.573465,58.505852,43.587228,52.009726,77.913660,41.354027,60.986385,20.157620,186.8205,42.696899,57.420403,70.802406
4,men/000004.png,104.736869,93.577234,106.010664,40.026016,33.198243,56.753582,37.691793,49.763331,73.619604,38.421023,58.549413,17.662700,176.7890,40.444499,51.284504,67.094300

In [7]:
preprocess_input = {
    "VGG19": vgg19.preprocess_input,
    "ResNet50": resnet50.preprocess_input,
    "DenseNet121": densenet.preprocess_input
}

In [8]:
def preprocess_image(image_path, measurements, source,model):
    # Read the image
    image = tf.io.read_file(source+image_path)
    image = tf.image.decode_png(image, channels=3)

    # Resize the image to match ResNet50 input
    image = tf.image.resize(image, [224, 224])

    # Normalize the image
    image = preprocess_input[model](image)

    return image, measurements

In [9]:
def create_datasets(male_data,female_data,source, batch_size, train_size, val_size,preprocess_model):
    # Calcular cantidades

    source=source+ "/Images/"
    num_total = len(male_data) # misma cantidad que female 50k
    num_train = int(num_total * train_size)
    num_val = int(num_total * val_size)
    num_test = num_total - num_train - num_val

    male_dataset = tf.data.Dataset.from_tensor_slices((male_data["ID"].values,male_data.drop(columns=["ID"]).values))
    male_dataset = male_dataset.shuffle(buffer_size=len(male_data),seed=34,reshuffle_each_iteration=True)
    test_dataset_male = male_dataset.take(num_test)
    male_dataset =  male_dataset.skip(num_test)

    female_dataset = tf.data.Dataset.from_tensor_slices((female_data["ID"].values,female_data.drop(columns=["ID"]).values))
    female_dataset = female_dataset.shuffle(buffer_size=len(female_data),seed=34,reshuffle_each_iteration=True)
    test_dataset_female = female_dataset.take(num_test)
    female_dataset =  female_dataset.skip(num_test)


    # Unir ambos datasets
    combined_dataset = male_dataset.concatenate(female_dataset)
    combined_dataset = combined_dataset.shuffle(buffer_size=(len(male_data) + len(female_data) - 2*num_test),seed=34,reshuffle_each_iteration=True)

    train_dataset = combined_dataset.take(num_train*2)
    val_dataset = combined_dataset.skip(num_train*2).take(num_val*2)


    # Preprocesamiento y batching
    train_dataset = train_dataset.map(lambda x, y: preprocess_image(x, y, source,preprocess_model),
                                      num_parallel_calls=tf.data.AUTOTUNE).batch(batch_size).prefetch(tf.data.AUTOTUNE)

    val_dataset = val_dataset.map(lambda x, y: preprocess_image(x, y, source,preprocess_model),
                                  num_parallel_calls=tf.data.AUTOTUNE).batch(batch_size).prefetch(tf.data.AUTOTUNE)

    test_dataset_male = test_dataset_male.map(lambda x, y: preprocess_image(x, y, source,preprocess_model),
                                    num_parallel_calls=tf.data.AUTOTUNE).batch(batch_size).prefetch(tf.data.AUTOTUNE)

    test_dataset_female = test_dataset_female.map(lambda x, y: preprocess_image(x, y, source,preprocess_model),
                                    num_parallel_calls=tf.data.AUTOTUNE).batch(batch_size).prefetch(tf.data.AUTOTUNE)

    test_dataset_total= test_dataset_male.concatenate(test_dataset_female)

    return train_dataset, val_dataset, test_dataset_male, test_dataset_female, test_dataset_total

# 4. Model

## Training

In [10]:
encoder_names = [
    #VGG19,
    ResNet50,
    #DenseNet121
]

In [11]:
def get_model(encoder_name):

  encoder=encoder_name(weights="imagenet", include_top=False, input_shape=(224, 224, 3))

  x = encoder.output
  x = Flatten()(x)
  encoder = Model(inputs=encoder.input, outputs=x)
  inp = Input(shape=(224, 224, 3))
  x = inp
  encoder.trainable = False
  x = encoder(x)

  # Capas densas adicionales con BatchNorm y Dropout
  x = Dense(1024, activation='relu')(x)
  x = BatchNormalization()(x)

  x = Dense(512, activation='relu')(x)
  x = BatchNormalization()(x)

  x = Dense(128, activation='relu')(x)
  x = BatchNormalization()(x)

  # Capa de salida para regresión (16 salidas)
  output = Dense(16)(x)

  # Crear el modelo final
  model = Model(inputs=inp, outputs=output)

  return model

In [12]:
def predict_measurements_and_evaluate(dataset, model, target_size=(224, 224)):
    mae = tf.keras.losses.MeanAbsoluteError()
    mse = tf.keras.losses.MeanSquaredError()

    y_trues = []
    y_preds = []

    for batch_x, batch_y in dataset:
        preds = model.predict(batch_x, verbose=0)
        y_preds.append(preds)
        y_trues.append(batch_y.numpy())

    y_preds = np.vstack(y_preds)
    y_trues = np.vstack(y_trues)

    col_names = [
        "chest_circ", "waist_circ", "pelvis_circ", "neck_circ", "bicep_circ", "thigh_circ",
        "knee_circ", "arm_length", "leg_length", "calf_length", "head_circ", "wrist_circ",
        "arm_span", "shoulders_width", "torso_length", "inner_leg"
    ]

    all_mae = []
    all_mse = []
    for i in range(y_preds.shape[1]):
        mae_val = mae(y_trues[:, i], y_preds[:, i]).numpy()
        mse_val = mse(y_trues[:, i], y_preds[:, i]).numpy()
        all_mae.append(mae_val)
        all_mse.append(mse_val)
        print(f"MAE for {col_names[i]}: {mae_val}, MSE for {col_names[i]}: {mse_val}")

    mean_mae = np.mean(all_mae)
    mean_mse = np.mean(all_mse)
    print(f"Mean MAE: {mean_mae}, Mean MSE: {mean_mse}")

    return mean_mae, mean_mse

In [14]:
results_df = pd.DataFrame(columns=["mean_mae", "mean_mse"])
for encoder in encoder_names:
    encoder_name=encoder.__name__
    train_generator,validation_generator,test_generator_male,test_generator_female,test_generator_total=create_datasets(male_data,female_data,path, batch_size, train_size, val_size,encoder_name)
    encoder_name=encoder.__name__
    model = get_model(encoder)
    stopping = EarlyStopping(
        monitor="val_loss",
        min_delta=0,
        patience=10,
        verbose=0,
        mode="auto",
        baseline=None,
        restore_best_weights=True
    )
    model.compile(Adam(learning_rate=1e-4),
        loss='mean_absolute_error', metrics=['mean_absolute_percentage_error']
        )


    model.fit(train_generator,
              epochs=100,
              validation_data = validation_generator,
              callbacks=[ stopping],
              )

    model.save(save_path + f'/model_{encoder_name}.keras')
    print(f"backbone model:{encoder_name}")
    print("-" * 40)
    print("Results for male test dataset")
    predict_measurements_and_evaluate(test_generator_male, model, (224,224))
    print("\n")
    print("Results for female test dataset")
    predict_measurements_and_evaluate(test_generator_female, model, (224,224))
    print("\n")
    print("Results for both male and female test datasets")
    mean_mae, mean_mse = predict_measurements_and_evaluate(test_generator_total, model, (224,224))

    row_name = f"model_{encoder_name}"
    results_df.loc[row_name] = [mean_mae, mean_mse]


    print("-" * 40)
    print("\n")

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2758s 13s/step - loss: 64.2481 - mean_absolute_percentage_error: 99.9414 - val_loss: 63.9414 - val_mean_absolute_percentage_error: 99.4549
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 712s 4s/step - loss: 63.9852 - mean_absolute_percentage_error: 99.4140 - val_loss: 63.0180 - val_mean_absolute_percentage_error: 97.3382
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 234s 1s/step - loss: 63.4837 - mean_absolute_percentage_error: 98.3376 - val_loss: 61.4691 - val_mean_absolute_percentage_error: 94.0297
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 133s 661ms/step - loss: 62.7207 - mean_absolute_percentage_error: 96.6681 - val_loss: 60.0511 - val_mean_absolute_percentage_error: 91.1465
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 121s 603ms/step - loss: 61.7498 - mean_absolute_percentage_error: 94.5646 - val_loss: 53.4174 - val_mean_absolute_percentage_error: 77.0418
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 119s 590ms/step - loss: 60.5137 - mean_absolute_percentage_error: 92.1925 - val_loss: 65.2774 - val_mean_absolute_percentage_error: 101.5490
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 119s 594ms/step - loss: 59.0953 - mean_absolute_percentage_error: 88.7621 - val_loss: 57.5652 - val_mean_absolute_percentage_error: 85.6305
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 586ms/step - loss: 57.4695 - mean_absolute_percentage_error: 85.3717 - val_loss: 56.0831 - val_mean_absolute_percentage_error: 82.5282
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 586ms/step - loss: 55.6358 - mean_absolute_percentage_error: 81.5908 - val_loss: 53.8004 - val_mean_absolute_percentage_error: 77.8048
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 53.6518 - mean_absolute_percentage_error: 77.5400 - val_loss: 54.9251 - val_mean_absolute_percentage_error: 80.3912
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 51.4996 - mean_absolute_percentage_error: 72.8581 - val_loss: 51.1712 - val_mean_absolute_percentage_error: 72.1535
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 49.2341 - mean_absolute_percentage_error: 68.0174 - val_loss: 47.8022 - val_mean_absolute_percentage_error: 65.2297
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 46.9271 - mean_absolute_percentage_error: 63.4722 - val_loss: 45.6086 - val_mean_absolute_percentage_error: 60.9328
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 44.5594 - mean_absolute_percentage_error: 59.1340 - val_loss: 42.2844 - val_mean_absolute_percentage_error: 54.8898
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 42.0960 - mean_absolute_percentage_error: 54.5367 - val_loss: 40.3380 - val_mean_absolute_percentage_error: 51.2144
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 39.4448 - mean_absolute_percentage_error: 49.6116 - val_loss: 37.6146 - val_mean_absolute_percentage_error: 46.2650
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 36.7361 - mean_absolute_percentage_error: 44.5751 - val_loss: 34.9585 - val_mean_absolute_percentage_error: 41.5158
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 586ms/step - loss: 34.0391 - mean_absolute_percentage_error: 39.9251 - val_loss: 32.2876 - val_mean_absolute_percentage_error: 36.9803
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 31.4233 - mean_absolute_percentage_error: 35.4339 - val_loss: 30.0331 - val_mean_absolute_percentage_error: 33.1512
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 28.9843 - mean_absolute_percentage_error: 31.4855 - val_loss: 27.6859 - val_mean_absolute_percentage_error: 29.5014
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 26.9566 - mean_absolute_percentage_error: 28.4422 - val_loss: 25.7387 - val_mean_absolute_percentage_error: 26.6606
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 25.0961 - mean_absolute_percentage_error: 25.8071 - val_loss: 23.6149 - val_mean_absolute_percentage_error: 23.7511
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 23.1788 - mean_absolute_percentage_error: 23.1413 - val_loss: 21.7212 - val_mean_absolute_percentage_error: 21.1813
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 586ms/step - loss: 21.2286 - mean_absolute_percentage_error: 20.4657 - val_loss: 20.1835 - val_mean_absolute_percentage_error: 19.0738
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 19.5896 - mean_absolute_percentage_error: 18.3696 - val_loss: 18.6326 - val_mean_absolute_percentage_error: 17.1951
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 18.2677 - mean_absolute_percentage_error: 16.7986 - val_loss: 17.4480 - val_mean_absolute_percentage_error: 15.8369
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 17.1001 - mean_absolute_percentage_error: 15.4980 - val_loss: 16.2632 - val_mean_absolute_percentage_error: 14.5830
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 15.9332 - mean_absolute_percentage_error: 14.2508 - val_loss: 15.0631 - val_mean_absolute_percentage_error: 13.3019
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 14.7515 - mean_absolute_percentage_error: 12.9907 - val_loss: 13.7422 - val_mean_absolute_percentage_error: 11.9593
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 13.5110 - mean_absolute_percentage_error: 11.6645 - val_loss: 12.4114 - val_mean_absolute_percentage_error: 10.5607
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 12.2199 - mean_absolute_percentage_error: 10.3316 - val_loss: 11.3021 - val_mean_absolute_percentage_error: 9.4001
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 11.0520 - mean_absolute_percentage_error: 9.1676 - val_loss: 10.2881 - val_mean_absolute_percentage_error: 8.4631
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 10.1090 - mean_absolute_percentage_error: 8.2791 - val_loss: 9.4750 - val_mean_absolute_percentage_error: 7.7263
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 9.3232 - mean_absolute_percentage_error: 7.5546 - val_loss: 8.7359 - val_mean_absolute_percentage_error: 7.0332
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 8.5521 - mean_absolute_percentage_error: 6.8796 - val_loss: 8.0259 - val_mean_absolute_percentage_error: 6.4756
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 7.8002 - mean_absolute_percentage_error: 6.2367 - val_loss: 7.2380 - val_mean_absolute_percentage_error: 5.7951
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 7.1018 - mean_absolute_percentage_error: 5.6460 - val_loss: 6.7401 - val_mean_absolute_percentage_error: 5.4407
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 6.4964 - mean_absolute_percentage_error: 5.1612 - val_loss: 6.0999 - val_mean_absolute_percentage_error: 4.8151
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 5.9962 - mean_absolute_percentage_error: 4.7648 - val_loss: 5.6463 - val_mean_absolute_percentage_error: 4.4838
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 5.6049 - mean_absolute_percentage_error: 4.4601 - val_loss: 5.3745 - val_mean_absolute_percentage_error: 4.3137
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 5.3136 - mean_absolute_percentage_error: 4.2521 - val_loss: 5.1200 - val_mean_absolute_percentage_error: 4.1272
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 5.0771 - mean_absolute_percentage_error: 4.0935 - val_loss: 4.9035 - val_mean_absolute_percentage_error: 3.9616
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 4.8547 - mean_absolute_percentage_error: 3.9380 - val_loss: 4.7223 - val_mean_absolute_percentage_error: 3.8173
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 4.6529 - mean_absolute_percentage_error: 3.7928 - val_loss: 4.5196 - val_mean_absolute_percentage_error: 3.7124
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 4.4581 - mean_absolute_percentage_error: 3.6698 - val_loss: 4.3077 - val_mean_absolute_percentage_error: 3.5668
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 4.2607 - mean_absolute_percentage_error: 3.5406 - val_loss: 4.1034 - val_mean_absolute_percentage_error: 3.4194
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 4.0542 - mean_absolute_percentage_error: 3.4158 - val_loss: 3.8747 - val_mean_absolute_percentage_error: 3.2653
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 3.8513 - mean_absolute_percentage_error: 3.2867 - val_loss: 3.6773 - val_mean_absolute_percentage_error: 3.1445
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 3.6331 - mean_absolute_percentage_error: 3.1457 - val_loss: 3.4489 - val_mean_absolute_percentage_error: 3.0250
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 3.4268 - mean_absolute_percentage_error: 3.0280 - val_loss: 3.2341 - val_mean_absolute_percentage_error: 2.8964
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 3.2063 - mean_absolute_percentage_error: 2.8955 - val_loss: 3.0084 - val_mean_absolute_percentage_error: 2.7297
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 2.9805 - mean_absolute_percentage_error: 2.7547 - val_loss: 2.7786 - val_mean_absolute_percentage_error: 2.6233
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 2.7458 - mean_absolute_percentage_error: 2.6197 - val_loss: 2.5425 - val_mean_absolute_percentage_error: 2.4910
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 2.5125 - mean_absolute_percentage_error: 2.4843 - val_loss: 2.2835 - val_mean_absolute_percentage_error: 2.2927
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 2.2599 - mean_absolute_percentage_error: 2.3223 - val_loss: 2.0513 - val_mean_absolute_percentage_error: 2.1692
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 2.0328 - mean_absolute_percentage_error: 2.2032 - val_loss: 1.7981 - val_mean_absolute_percentage_error: 2.0201
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 1.7829 - mean_absolute_percentage_error: 2.0463 - val_loss: 1.5930 - val_mean_absolute_percentage_error: 1.9272
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 1.5445 - mean_absolute_percentage_error: 1.9067 - val_loss: 1.3479 - val_mean_absolute_percentage_error: 1.7932
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 1.3173 - mean_absolute_percentage_error: 1.7764 - val_loss: 1.1552 - val_mean_absolute_percentage_error: 1.7106
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 1.1305 - mean_absolute_percentage_error: 1.6893 - val_loss: 1.0248 - val_mean_absolute_percentage_error: 1.6802
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 0.9817 - mean_absolute_percentage_error: 1.6056 - val_loss: 0.8724 - val_mean_absolute_percentage_error: 1.5392
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 0.9014 - mean_absolute_percentage_error: 1.5714 - val_loss: 0.8168 - val_mean_absolute_percentage_error: 1.4689
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 0.8490 - mean_absolute_percentage_error: 1.5287 - val_loss: 0.7910 - val_mean_absolute_percentage_error: 1.4595
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 0.8186 - mean_absolute_percentage_error: 1.4935 - val_loss: 0.7907 - val_mean_absolute_percentage_error: 1.4541
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 0.8075 - mean_absolute_percentage_error: 1.4816 - val_loss: 0.7605 - val_mean_absolute_percentage_error: 1.4190
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 0.7947 - mean_absolute_percentage_error: 1.4651 - val_loss: 0.7483 - val_mean_absolute_percentage_error: 1.4091
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7996 - mean_absolute_percentage_error: 1.4717 - val_loss: 0.7966 - val_mean_absolute_percentage_error: 1.4886
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 0.7821 - mean_absolute_percentage_error: 1.4433 - val_loss: 0.7303 - val_mean_absolute_percentage_error: 1.3865
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7668 - mean_absolute_percentage_error: 1.4211 - val_loss: 0.7618 - val_mean_absolute_percentage_error: 1.4265
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7719 - mean_absolute_percentage_error: 1.4299 - val_loss: 0.7487 - val_mean_absolute_percentage_error: 1.3913
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7687 - mean_absolute_percentage_error: 1.4257 - val_loss: 0.7884 - val_mean_absolute_percentage_error: 1.4641
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 0.7658 - mean_absolute_percentage_error: 1.4206 - val_loss: 0.7262 - val_mean_absolute_percentage_error: 1.3736
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 586ms/step - loss: 0.7680 - mean_absolute_percentage_error: 1.4248 - val_loss: 0.7408 - val_mean_absolute_percentage_error: 1.3802
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7554 - mean_absolute_percentage_error: 1.4048 - val_loss: 0.7348 - val_mean_absolute_percentage_error: 1.3705
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7508 - mean_absolute_percentage_error: 1.3962 - val_loss: 0.7291 - val_mean_absolute_percentage_error: 1.3700
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7484 - mean_absolute_percentage_error: 1.3925 - val_loss: 0.7418 - val_mean_absolute_percentage_error: 1.3977
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 0.7535 - mean_absolute_percentage_error: 1.4004 - val_loss: 0.7070 - val_mean_absolute_percentage_error: 1.3336
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 586ms/step - loss: 0.7342 - mean_absolute_percentage_error: 1.3733 - val_loss: 0.7024 - val_mean_absolute_percentage_error: 1.3275
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 588ms/step - loss: 0.7395 - mean_absolute_percentage_error: 1.3804 - val_loss: 0.6727 - val_mean_absolute_percentage_error: 1.2953
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 584ms/step - loss: 0.7381 - mean_absolute_percentage_error: 1.3769 - val_loss: 0.6973 - val_mean_absolute_percentage_error: 1.3204
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7263 - mean_absolute_percentage_error: 1.3570 - val_loss: 0.7185 - val_mean_absolute_percentage_error: 1.3601
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7230 - mean_absolute_percentage_error: 1.3545 - val_loss: 0.6988 - val_mean_absolute_percentage_error: 1.3477
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7275 - mean_absolute_percentage_error: 1.3591 - val_loss: 0.6918 - val_mean_absolute_percentage_error: 1.3061
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7239 - mean_absolute_percentage_error: 1.3544 - val_loss: 0.6861 - val_mean_absolute_percentage_error: 1.3144
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 586ms/step - loss: 0.7092 - mean_absolute_percentage_error: 1.3314 - val_loss: 0.6653 - val_mean_absolute_percentage_error: 1.2694
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7177 - mean_absolute_percentage_error: 1.3417 - val_loss: 0.7241 - val_mean_absolute_percentage_error: 1.3566
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 586ms/step - loss: 0.7114 - mean_absolute_percentage_error: 1.3311 - val_loss: 0.7142 - val_mean_absolute_percentage_error: 1.3485
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 0.7151 - mean_absolute_percentage_error: 1.3384 - val_loss: 0.7246 - val_mean_absolute_percentage_error: 1.3833
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 584ms/step - loss: 0.7079 - mean_absolute_percentage_error: 1.3259 - val_loss: 0.6918 - val_mean_absolute_percentage_error: 1.3347
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 586ms/step - loss: 0.7097 - mean_absolute_percentage_error: 1.3297 - val_loss: 0.6789 - val_mean_absolute_percentage_error: 1.3127
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7122 - mean_absolute_percentage_error: 1.3301 - val_loss: 0.6924 - val_mean_absolute_percentage_error: 1.3219
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7039 - mean_absolute_percentage_error: 1.3196 - val_loss: 0.7205 - val_mean_absolute_percentage_error: 1.3691
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.7093 - mean_absolute_percentage_error: 1.3274 - val_loss: 0.6755 - val_mean_absolute_percentage_error: 1.2825
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 117s 584ms/step - loss: 0.7039 - mean_absolute_percentage_error: 1.3175 - val_loss: 0.6868 - val_mean_absolute_percentage_error: 1.3115
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 587ms/step - loss: 0.6871 - mean_absolute_percentage_error: 1.2926 - val_loss: 0.6403 - val_mean_absolute_percentage_error: 1.2371
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 117s 584ms/step - loss: 0.7026 - mean_absolute_percentage_error: 1.3173 - val_loss: 0.6976 - val_mean_absolute_percentage_error: 1.3191
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.6909 - mean_absolute_percentage_error: 1.2981 - val_loss: 0.7024 - val_mean_absolute_percentage_error: 1.3173
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.6882 - mean_absolute_percentage_error: 1.2919 - val_loss: 0.6816 - val_mean_absolute_percentage_error: 1.3107
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 585ms/step - loss: 0.6976 - mean_absolute_percentage_error: 1.3072 - val_loss: 0.6624 - val_mean_absolute_percentage_error: 1.2649
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 118s 586ms/step - loss: 0.6985 - mean_absolute_percentage_error: 1.3074 - val_loss: 0.6732 - val_mean_absolute_percentage_error: 1.2893
backbone model:ResNet50
----------------------------------------
Results for male test dataset
MAE for chest_circ: 1.0830509662628174, MSE for chest_circ: 1.9742783308029175
MAE for waist_circ: 1.1779338121414185, MSE for waist_circ: 2.300794839859009
MAE for pelvis_circ: 0.9649011492729187, MSE for pelvis_circ: 1.5707985162734985
MAE for neck_circ: 0.716497004032135, MSE for neck_circ: 0.8752140402793884
MAE for bicep_circ: 0.5395249724388123, MSE for bicep_circ: 0.5028060078620911
MAE for thigh_circ: 0.8135558366775513, MSE for thigh_circ: 1.092661738395691
MAE for knee_circ: 0.6394065022468567, MSE for knee_circ: 0.6473746299743652
MAE for arm_length: 0.36602911353111267, MSE for arm_length: 0.2123720645904541
MAE for leg_length: 0.38209569454193115, MSE for leg_length: 0.23885786533355713
MAE for calf_length: 0.26140934228897095, MSE for calf_length: 0.1108236312866211
MAE for head_circ: 0.5565873980522156, MSE for head_circ: 0.5148109793663025
MAE for wrist_circ: 0.33695730566978455, MSE for wrist_circ: 0.19299261271953583
MAE for arm_span: 0.645484983921051, MSE for arm_span: 0.6695947647094727
MAE for shoulders_width: 0.3384583294391632, MSE for shoulders_width: 0.18782180547714233
MAE for torso_length: 0.43433019518852234, MSE for torso_length: 0.30387428402900696
MAE for inner_leg: 0.7950484156608582, MSE for inner_leg: 1.0087919235229492
Mean MAE: 0.6282044649124146, Mean MSE: 0.7752417325973511


Results for female test dataset
MAE for chest_circ: 1.3502792119979858, MSE for chest_circ: 3.141310453414917
MAE for waist_circ: 1.2826595306396484, MSE for waist_circ: 2.770559072494507
MAE for pelvis_circ: 0.932992160320282, MSE for pelvis_circ: 1.4730312824249268
MAE for neck_circ: 0.6332822442054749, MSE for neck_circ: 0.6802982687950134
MAE for bicep_circ: 0.5997982025146484, MSE for bicep_circ: 0.606534481048584
MAE for thigh_circ: 0.8028526902198792, MSE for thigh_circ: 1.0785142183303833
MAE for knee_circ: 0.6158007979393005, MSE for knee_circ: 0.6230852603912354
MAE for arm_length: 0.3933466672897339, MSE for arm_length: 0.250419944524765

In [ ]:
results_df.to_excel(save_path+"/resultados.xlsx")

In [15]:
results_df

                mean_mae  mean_mse
model_ResNet50  0.640874  0.824705

# Testing